// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpcbuild.proto

package grpcbuild

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type InitRequest struct {
	Dir                  string   `protobuf:"bytes,1,opt,name=Dir,proto3" json:"Dir,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitRequest) Reset()         { *m = InitRequest{} }
func (m *InitRequest) String() string { return proto.CompactTextString(m) }
func (*InitRequest) ProtoMessage()    {}
func (*InitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_96cb7cdd0dd8a03f, []int{0}
}

func (m *InitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitRequest.Unmarshal(m, b)
}
func (m *InitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitRequest.Marshal(b, m, deterministic)
}
func (m *InitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitRequest.Merge(m, src)
}
func (m *InitRequest) XXX_Size() int {
	return xxx_messageInfo_InitRequest.Size(m)
}
func (m *InitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InitRequest proto.InternalMessageInfo

func (m *InitRequest) GetDir() string {
	if m != nil {
		return m.Dir
	}
	return ""
}

type InitResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitResponse) Reset()         { *m = InitResponse{} }
func (m *InitResponse) String() string { return proto.CompactTextString(m) }
func (*InitResponse) ProtoMessage()    {}
func (*InitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_96cb7cdd0dd8a03f, []int{1}
}

func (m *InitResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitResponse.Unmarshal(m, b)
}
func (m *InitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitResponse.Marshal(b, m, deterministic)
}
func (m *InitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitResponse.Merge(m, src)
}
func (m *InitResponse) XXX_Size() int {
	return xxx_messageInfo_InitResponse.Size(m)
}
func (m *InitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InitResponse proto.InternalMessageInfo

type File struct {
	Filename             string   `protobuf:"bytes,1,opt,name=Filename,proto3" json:"Filename,omitempty"`
	Dir                  string   `protobuf:"bytes,2,opt,name=Dir,proto3" json:"Dir,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_96cb7cdd0dd8a03f, []int{2}
}

func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (m *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(m, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *File) GetDir() string {
	if m != nil {
		return m.Dir
	}
	return ""
}

func (m *File) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type SendRequest struct {
	Files                []*File  `protobuf:"bytes,1,rep,name=Files,proto3" json:"Files,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendRequest) Reset()         { *m = SendRequest{} }
func (m *SendRequest) String() string { return proto.CompactTextString(m) }
func (*SendRequest) ProtoMessage()    {}
func (*SendRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_96cb7cdd0dd8a03f, []int{3}
}

func (m *SendRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendRequest.Unmarshal(m, b)
}
func (m *SendRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendRequest.Marshal(b, m, deterministic)
}
func (m *SendRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendRequest.Merge(m, src)
}
func (m *SendRequest) XXX_Size() int {
	return xxx_messageInfo_SendRequest.Size(m)
}
func (m *SendRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendRequest proto.InternalMessageInfo

func (m *SendRequest) GetFiles() []*File {
	if m != nil {
		return m.Files
	}
	return nil
}

type SendResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendResponse) Reset()         { *m = SendResponse{} }
func (m *SendResponse) String() string { return proto.CompactTextString(m) }
func (*SendResponse) ProtoMessage()    {}
func (*SendResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_96cb7cdd0dd8a03f, []int{4}
}

func (m *SendResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendResponse.Unmarshal(m, b)
}
func (m *SendResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendResponse.Marshal(b, m, deterministic)
}
func (m *SendResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendResponse.Merge(m, src)
}
func (m *SendResponse) XXX_Size() int {
	return xxx_messageInfo_SendResponse.Size(m)
}
func (m *SendResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendResponse proto.InternalMessageInfo

type Cmd struct {
	Path                 string   `protobuf:"bytes,1,opt,name=Path,proto3" json:"Path,omitempty"`
	Args                 []string `protobuf:"bytes,2,rep,name=Args,proto3" json:"Args,omitempty"`
	Env                  []string `protobuf:"bytes,3,rep,name=Env,proto3" json:"Env,omitempty"`
	Dir                  string   `protobuf:"bytes,4,opt,name=Dir,proto3" json:"Dir,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Cmd) Reset()         { *m = Cmd{} }
func (m *Cmd) String() string { return proto.CompactTextString(m) }
func (*Cmd) ProtoMessage()    {}
func (*Cmd) Descriptor() ([]byte, []int) {
	return fileDescriptor_96cb7cdd0dd8a03f, []int{5}
}

func (m *Cmd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cmd.Unmarshal(m, b)
}
func (m *Cmd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cmd.Marshal(b, m, deterministic)
}
func (m *Cmd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cmd.Merge(m, src)
}
func (m *Cmd) XXX_Size() int {
	return xxx_messageInfo_Cmd.Size(m)
}
func (m *Cmd) XXX_DiscardUnknown() {
	xxx_messageInfo_Cmd.DiscardUnknown(m)
}

var xxx_messageInfo_Cmd proto.InternalMessageInfo

func (m *Cmd) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Cmd) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *Cmd) GetEnv() []string {
	if m != nil {
		return m.Env
	}
	return nil
}

func (m *Cmd) GetDir() string {
	if m != nil {
		return m.Dir
	}
	return ""
}

type ExecRequest struct {
	Cmds                 []*Cmd   `protobuf:"bytes,1,rep,name=Cmds,proto3" json:"Cmds,omitempty"`
	Files                []string `protobuf:"bytes,2,rep,name=Files,proto3" json:"Files,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecRequest) Reset()         { *m = ExecRequest{} }
func (m *ExecRequest) String() string { return proto.CompactTextString(m) }
func (*ExecRequest) ProtoMessage()    {}
func (*ExecRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_96cb7cdd0dd8a03f, []int{6}
}

func (m *ExecRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecRequest.Unmarshal(m, b)
}
func (m *ExecRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecRequest.Marshal(b, m, deterministic)
}
func (m *ExecRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecRequest.Merge(m, src)
}
func (m *ExecRequest) XXX_Size() int {
	return xxx_messageInfo_ExecRequest.Size(m)
}
func (m *ExecRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExecRequest proto.InternalMessageInfo

func (m *ExecRequest) GetCmds() []*Cmd {
	if m != nil {
		return m.Cmds
	}
	return nil
}

func (m *ExecRequest) GetFiles() []string {
	if m != nil {
		return m.Files
	}
	return nil
}

type ExecResponse struct {
	ExitCode             int32    `protobuf:"varint,1,opt,name=ExitCode,proto3" json:"ExitCode,omitempty"`
	Stdout               []byte   `protobuf:"bytes,2,opt,name=Stdout,proto3" json:"Stdout,omitempty"`
	Stderr               []byte   `protobuf:"bytes,3,opt,name=Stderr,proto3" json:"Stderr,omitempty"`
	Files                []*File  `protobuf:"bytes,4,rep,name=Files,proto3" json:"Files,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecResponse) Reset()         { *m = ExecResponse{} }
func (m *ExecResponse) String() string { return proto.CompactTextString(m) }
func (*ExecResponse) ProtoMessage()    {}
func (*ExecResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_96cb7cdd0dd8a03f, []int{7}
}

func (m *ExecResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecResponse.Unmarshal(m, b)
}
func (m *ExecResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecResponse.Marshal(b, m, deterministic)
}
func (m *ExecResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecResponse.Merge(m, src)
}
func (m *ExecResponse) XXX_Size() int {
	return xxx_messageInfo_ExecResponse.Size(m)
}
func (m *ExecResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExecResponse proto.InternalMessageInfo

func (m *ExecResponse) GetExitCode() int32 {
	if m != nil {
		return m.ExitCode
	}
	return 0
}

func (m *ExecResponse) GetStdout() []byte {
	if m != nil {
		return m.Stdout
	}
	return nil
}

func (m *ExecResponse) GetStderr() []byte {
	if m != nil {
		return m.Stderr
	}
	return nil
}

func (m *ExecResponse) GetFiles() []*File {
	if m != nil {
		return m.Files
	}
	return nil
}

func init() {
	proto.RegisterType((*InitRequest)(nil), "grpcbuild.InitRequest")
	proto.RegisterType((*InitResponse)(nil), "grpcbuild.InitResponse")
	proto.RegisterType((*File)(nil), "grpcbuild.File")
	proto.RegisterType((*SendRequest)(nil), "grpcbuild.SendRequest")
	proto.RegisterType((*SendResponse)(nil), "grpcbuild.SendResponse")
	proto.RegisterType((*Cmd)(nil), "grpcbuild.Cmd")
	proto.RegisterType((*ExecRequest)(nil), "grpcbuild.ExecRequest")
	proto.RegisterType((*ExecResponse)(nil), "grpcbuild.ExecResponse")
}

func init() { proto.RegisterFile("grpcbuild.proto", fileDescriptor_96cb7cdd0dd8a03f) }

var fileDescriptor_96cb7cdd0dd8a03f = []byte{
	// 354 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0xcf, 0x4e, 0xc2, 0x40,
	0x10, 0xc6, 0x29, 0x2d, 0x44, 0xa6, 0x0d, 0x98, 0x8d, 0xc1, 0x86, 0x8b, 0x4d, 0x13, 0x13, 0x4e,
	0x1c, 0xd0, 0x8b, 0x47, 0x2d, 0x88, 0xde, 0x74, 0x79, 0x82, 0xc2, 0x6e, 0xb0, 0x09, 0xfd, 0xe3,
	0x76, 0x31, 0x5c, 0x7d, 0x2f, 0x1f, 0xce, 0xcc, 0xee, 0xf6, 0x5f, 0x4c, 0x3c, 0x31, 0xf3, 0xed,
	0x7e, 0xb3, 0x3f, 0xbe, 0x29, 0x4c, 0x0e, 0xa2, 0xd8, 0xef, 0x4e, 0xc9, 0x91, 0x2d, 0x0a, 0x91,
	0xcb, 0x9c, 0x8c, 0x6a, 0x21, 0xbc, 0x01, 0xf7, 0x35, 0x4b, 0x24, 0xe5, 0x9f, 0x27, 0x5e, 0x4a,
	0x72, 0x09, 0xf6, 0x2a, 0x11, 0xbe, 0x15, 0x58, 0xf3, 0x11, 0xc5, 0x32, 0x1c, 0x83, 0xa7, 0x2f,
	0x94, 0x45, 0x9e, 0x95, 0x3c, 0x7c, 0x01, 0xe7, 0x39, 0x39, 0x72, 0x32, 0x83, 0x0b, 0xfc, 0xcd,
	0xe2, 0x94, 0x9b, 0xeb, 0x75, 0x5f, 0x4d, 0xe9, 0xd7, 0x53, 0x08, 0x01, 0x67, 0x15, 0xcb, 0xd8,
	0xb7, 0x03, 0x6b, 0xee, 0x51, 0x55, 0x87, 0xf7, 0xe0, 0x6e, 0x79, 0xc6, 0xaa, 0xa7, 0x6f, 0x61,
	0x80, 0x03, 0x4a, 0xdf, 0x0a, 0xec, 0xb9, 0xbb, 0x9c, 0x2c, 0x1a, 0x6a, 0xd4, 0xa9, 0x3e, 0x45,
	0x1e, 0xed, 0x32, 0x3c, 0xef, 0x60, 0x47, 0x29, 0xc3, 0x07, 0xde, 0x62, 0xf9, 0x61, 0x50, 0x54,
	0x8d, 0xda, 0xa3, 0x38, 0x94, 0x7e, 0x3f, 0xb0, 0x51, 0xc3, 0x1a, 0xd1, 0xd6, 0xd9, 0x97, 0x6f,
	0x2b, 0x09, 0xcb, 0x0a, 0xd6, 0x69, 0xfe, 0xf2, 0x06, 0xdc, 0xf5, 0x99, 0xef, 0x2b, 0xb0, 0x10,
	0x9c, 0x28, 0x65, 0x15, 0xd7, 0xb8, 0xc5, 0x15, 0xa5, 0x8c, 0xaa, 0x33, 0x72, 0x55, 0xc1, 0xeb,
	0xb7, 0x0c, 0xeb, 0xb7, 0x05, 0x9e, 0x9e, 0xa4, 0x61, 0x31, 0xb4, 0xf5, 0x39, 0x91, 0x51, 0xce,
	0x74, 0x68, 0x03, 0x5a, 0xf7, 0x64, 0x0a, 0xc3, 0xad, 0x64, 0xf9, 0x49, 0xaa, 0xdc, 0x3c, 0x6a,
	0x3a, 0xa3, 0x73, 0x21, 0x4c, 0x78, 0xa6, 0x6b, 0xf2, 0x72, 0xfe, 0xcb, 0x6b, 0xf9, 0x63, 0xc1,
	0x68, 0x23, 0x8a, 0xfd, 0x13, 0x9e, 0x90, 0x07, 0x70, 0x70, 0x9b, 0x64, 0xda, 0xba, 0xdd, 0xda,
	0xff, 0xec, 0xfa, 0x8f, 0x6e, 0x62, 0xee, 0xa1, 0x15, 0x83, 0xef, 0x58, 0x5b, 0xfb, 0xeb, 0x58,
	0x3b, 0x1b, 0x52, 0x56, 0x8c, 0xa1, 0x63, 0x6d, 0x25, 0xdc, 0xb1, 0xb6, 0xf3, 0x0a, 0x7b, 0xbb,
	0xa1, 0xfa, 0x62, 0xef, 0x7e, 0x03, 0x00, 0x00, 0xff, 0xff, 0x6a, 0x5d, 0x77, 0x7a, 0xc4, 0x02,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GrpcBuildClient is the client API for GrpcBuild service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GrpcBuildClient interface {
	Init(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*InitResponse, error)
	Send(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*SendResponse, error)
	Exec(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (*ExecResponse, error)
}

type grpcBuildClient struct {
	cc *grpc.ClientConn
}

func NewGrpcBuildClient(cc *grpc.ClientConn) GrpcBuildClient {
	return &grpcBuildClient{cc}
}

func (c *grpcBuildClient) Init(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*InitResponse, error) {
	out := new(InitResponse)
	err := c.cc.Invoke(ctx, "/grpcbuild.GrpcBuild/Init", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcBuildClient) Send(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*SendResponse, error) {
	out := new(SendResponse)
	err := c.cc.Invoke(ctx, "/grpcbuild.GrpcBuild/Send", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcBuildClient) Exec(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (*ExecResponse, error) {
	out := new(ExecResponse)
	err := c.cc.Invoke(ctx, "/grpcbuild.GrpcBuild/Exec", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GrpcBuildServer is the server API for GrpcBuild service.
type GrpcBuildServer interface {
	Init(context.Context, *InitRequest) (*InitResponse, error)
	Send(context.Context, *SendRequest) (*SendResponse, error)
	Exec(context.Context, *ExecRequest) (*ExecResponse, error)
}

func RegisterGrpcBuildServer(s *grpc.Server, srv GrpcBuildServer) {
	s.RegisterService(&_GrpcBuild_serviceDesc, srv)
}

func _GrpcBuild_Init_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcBuildServer).Init(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcbuild.GrpcBuild/Init",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcBuildServer).Init(ctx, req.(*InitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrpcBuild_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcBuildServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcbuild.GrpcBuild/Send",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcBuildServer).Send(ctx, req.(*SendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrpcBuild_Exec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcBuildServer).Exec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcbuild.GrpcBuild/Exec",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcBuildServer).Exec(ctx, req.(*ExecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GrpcBuild_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpcbuild.GrpcBuild",
	HandlerType: (*GrpcBuildServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Init",
			Handler:    _GrpcBuild_Init_Handler,
		},
		{
			MethodName: "Send",
			Handler:    _GrpcBuild_Send_Handler,
		},
		{
			MethodName: "Exec",
			Handler:    _GrpcBuild_Exec_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpcbuild.proto",
}
